import pytest
import os
from unittest.mock import MagicMock, patch
from botocore.exceptions import ClientError
import app.config

# Mock the config settings to prevent actual S3 interactions
app.config.S3_ENDPOINT_URL = "http://localhost:9000"
app.config.S3_ACCESS_KEY = "test_key"
app.config.S3_SECRET_KEY = "test_secret"
app.config.S3_BUCKET_NAME = "test_bucket"
app.config.S3_REGION = "us-east-1"
# Do not mock STORAGE_MODE here globally so we can test both local and cloud modes
app.config.STORAGE_MODE = "cloud"

from app.core.storage import CloudStorage


def test_generate_signed_url_disabled():
    with patch("app.core.storage.STORAGE_MODE", "local"):
        storage = CloudStorage()
        storage.enabled = False
        url = storage.generate_signed_url("test_path.mp4")
        assert url is None


def test_generate_signed_url_success():
    with patch("app.core.storage.STORAGE_MODE", "cloud"):
        storage = CloudStorage()
        storage.enabled = True

        # Mock the s3 client generated by boto3
        mock_s3 = MagicMock()
        expected_url = "https://example.com/test_path.mp4?signature=123"
        mock_s3.generate_presigned_url.return_value = expected_url
        storage.s3 = mock_s3
        storage.bucket = "test_bucket"

        url = storage.generate_signed_url("test_path.mp4", expires_in=3600)

        # Assert url matches expected
        assert url == expected_url

        # Assert generate_presigned_url was called with correct parameters
        mock_s3.generate_presigned_url.assert_called_once_with(
            'get_object',
            Params={'Bucket': 'test_bucket', 'Key': 'test_path.mp4'},
            ExpiresIn=3600
        )


def test_generate_signed_url_client_error():
    with patch("app.core.storage.STORAGE_MODE", "cloud"):
        storage = CloudStorage()
        storage.enabled = True

        # Mock the s3 client generated by boto3
        mock_s3 = MagicMock()
        # Create a mock error response to instantiate ClientError correctly
        error_response = {'Error': {'Code': '500', 'Message': 'Error'}}
        mock_s3.generate_presigned_url.side_effect = ClientError(error_response, 'operation_name')

        storage.s3 = mock_s3
        storage.bucket = "test_bucket"

        # Use patch to suppress print to avoid cluttering test output
        with patch("builtins.print") as mock_print:
            url = storage.generate_signed_url("test_path.mp4")

            # Assert url is None when error is raised
            assert url is None

            # Assert error message was printed
            mock_print.assert_called_once()
            args, kwargs = mock_print.call_args
            assert "Error generating signed URL:" in args[0]
